<a href="https://colab.research.google.com/github/Parthjain2005/UCS420/blob/main/Assignment_4_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

add_result = arr + 2
multiply_result = arr * 3
divide_result = arr / 2

print("Original Array:", arr)
print("After Addition:", add_result)
print("After Multiplication:", multiply_result)
print("After Division:", divide_result)


Original Array: [1 2 3 4 5]
After Addition: [3 4 5 6 7]
After Multiplication: [ 3  6  9 12 15]
After Division: [0.5 1.  1.5 2.  2.5]


Q2

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed Array:", reversed_arr)

def most_frequent(arr):
    unique, counts = np.unique(arr, return_counts=True)
    most_frequent_value = unique[np.argmax(counts)]
    indices = np.where(arr == most_frequent_value)[0]
    return most_frequent_value, indices

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

most_freq_x, indices_x = most_frequent(x)
most_freq_y, indices_y = most_frequent(y)

print(f"Most Frequent in x: {most_freq_x}, Indices: {indices_x}")
print(f"Most Frequent in y: {most_freq_y}, Indices: {indices_y}")


Reversed Array: [5 4 6 3 2 1]
Most Frequent in x: 1, Indices: [0 5 7 8 9]
Most Frequent in y: 1, Indices: [0 1 2]


Q3

In [3]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

element_a = arr[0, 1]
element_b = arr[2, 0]

print("Element at 1st row, 2nd column:", element_a)
print("Element at 3rd row, 1st column:", element_b)


Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


Q4

In [5]:
import numpy as np

parth_jain = np.linspace(10, 100, 25)

print("Dimensions of array:", parth_jain.ndim)
print("Shape of array:", parth_jain.shape)
print("Total elements in array:", parth_jain.size)
print("Data type of each element:", parth_jain.dtype)
print("Total bytes consumed by array:", parth_jain.nbytes)

transposed_array = parth_jain.reshape(25, 1)
print("Transposed Array using reshape():\n", transposed_array)

transposed_using_T = parth_jain.T
print("Transposed Array using T attribute:\n", transposed_using_T)


Dimensions of array: 1
Shape of array: (25,)
Total elements in array: 25
Data type of each element: float64
Total bytes consumed by array: 200
Transposed Array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transposed Array using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


No, we cannot transpose a 1-D array using the .T attribute because .T works only for 2D or higher-dimensional arrays. However, we can achieve the transpose effect by reshaping it into a 2D column vector using .reshape(25, 1).

Q5

In [6]:
import numpy as np

ucs420_parth = np.array([[10, 20, 30, 40],
                          [50, 60, 70, 80],
                          [90, 15, 20, 35]])

mean_value = np.mean(ucs420_parth)
median_value = np.median(ucs420_parth)
max_value = np.max(ucs420_parth)
min_value = np.min(ucs420_parth)
unique_elements = np.unique(ucs420_parth)

reshaped_ucs420_parth = ucs420_parth.reshape(4, 3)

resized_ucs420_parth = np.resize(ucs420_parth, (2, 3))

print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_elements)
print("Reshaped Array (4x3):\n", reshaped_ucs420_parth)
print("Resized Array (2x3):\n", resized_ucs420_parth)


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
